---

plugins:
  - jest

env:
  node: true
  es2020: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  import/no-extraneous-dependencies: [2, { "devDependencies": true }]
  import/no-unresolved: 0
